#!/usr/bin/env bash

## Get data
get_weather() {
    weather=$(curl -sf "https://api.weatherapi.com/v1/current.json?key=YOUR_API&q=London&aqi=no")
    
    w_desc="Weather Unavailable"
    w_temp="-"
    w_feels="-"
    w_city="Nowhere"
    w_icon=""
    w_class=""

    if [ ! -z "$weather" ]; then
        w_desc=$(echo $weather | jq -r .current.condition.text)
        w_temp=$(echo $weather | jq -r .current.temp_c)
        w_feels=$(echo $weather | jq -r .current.feelslike_c)
        w_city=$(echo $weather | jq -r .location.name)

        w_icon_code=$(echo "$weather" | jq -r ".current.condition.icon")
        if   [[ "$w_icon_code" == *"day"* ]]; then w_class="d"
        elif [[ "$w_icon_code" == *"night"* ]]; then w_class="n"
        fi

        case $w_icon_code in
            *"113.png") w_icon=" ";;
            *"116.png") w_icon=" ";;
            *"119.png") w_icon=" ";;
            *"122.png") w_icon=" ";;
            *"143.png") w_icon=" ";;
            *"176.png") w_icon=" ";;
            *"179.png") w_icon=" ";;
            *"182.png") w_icon=" ";;
            *"185.png") w_icon=" ";;
            *"200.png") w_icon=" ";;
            *"227.png") w_icon=" ";;
            *"230.png") w_icon=" ";;
            *"248.png") w_icon=" ";;
            *"260.png") w_icon=" ";;
            *) w_icon="";;
        esac
    fi

    echo "{
        \"desc\": \"$w_desc\",
        \"temp\": \"$w_temp\",
        \"icon\": \"$w_icon\",
        \"class\": \"$w_class\",
        \"feels\": \"$w_feels\",
        \"city\": \"$w_city\"
    }"
}

echo "[
    $(get_weather $CITY)
]"